### ISSUE TITLE
Get camera feed

### ISSUE THREAD

**Issue by mubahmad** [mubahmad/BelleDolphine#3]
### Recognition and Direction

We need the camera feed to be displayed on the client connected to the Pi over SSH. It should recognize QR codes, doors, and IR lights (most likely showing a high intensity light as the camera has an IR mode that turns on automatically).

Finally using the function move() that takes [w,a,s,d] as input direct the robot to have the QR code, door, or the IR beacon in the horizontal center of the frame>

**Comment by levo-777** [comment]
something like this ? 
```python3
import cv2
import paramiko
import numpy as np

def capture_camera_feed():
    cap = cv2.VideoCapture(0)  # Use 0 for the default camera
    while True:
        ret, frame = cap.read()
        if not ret:
            break

        # Display the frame locally
        cv2.imshow('Camera Feed', frame)

        # Send the frame over SSH
        send_frame_over_ssh(frame)

        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    cap.release()
    cv2.destroyAllWindows()

def send_frame_over_ssh(frame):
    # Initialize SSH connection
    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    ssh.connect('your_ssh_host', username='your_username', password='your_password')

    # Encode the frame as JPEG before sending
    _, buffer = cv2.imencode('.jpg', frame)
    jpg_as_text = buffer.tobytes()

    # Send the frame data
    sftp = ssh.open_sftp()
    with sftp.file('/path/to/save/frame.jpg', 'wb') as f:
        f.write(jpg_as_text)

    # Close SSH connection
    ssh.close()

if __name__ == "__main__":
    capture_camera_feed()
```

**Comment by mubahmad** [comment]
Hi @levo-777, thank you very much for the comment.

I should've explained more what is needed in the issue but it was only for my friend who's getting started so he can get going hahaha.

I have edited the issue description, and it would be optimal if you create a PR.
